import {
  SiAngular,
  SiApachegroovy,
  SiApachekafka,
  SiCloudinary,
  SiCplusplus,
  SiDjango,
  SiDotnet,
  SiExpress,
  SiFlutter,
  SiGithub,
  SiHeroku,
  SiJavascript,
  SiJira,
  SiMongodb,
  SiNodedotjs,
  SiOpenjdk,
  SiPython,
  SiReact,
  SiRust,
  SiTailwindcss,
  SiTemporal,
  SiTypescript,
  SiVercel,
  SiXml,
  SiYaml,
} from "react-icons/si";
import { TbApi, TbBrandAzure, TbBrandCSharp, TbBrandOpenai, TbSql } from "react-icons/tb";
import { DiMsqlServer } from "react-icons/di";

// Brand icon + brand colour for each technology name used in the content.
export const techIcons = {
  "C#": { icon: TbBrandCSharp, color: "#a179dc" },
  ".NET": { icon: SiDotnet, color: "#8b5cf6" },
  TypeScript: { icon: SiTypescript, color: "#3178c6" },
  JavaScript: { icon: SiJavascript, color: "#f7df1e" },
  Python: { icon: SiPython, color: "#3776ab" },
  Java: { icon: SiOpenjdk, color: "#f89820" },
  "C++": { icon: SiCplusplus, color: "#00599c" },
  Rust: { icon: SiRust, color: "#dea584" },
  SQL: { icon: TbSql, color: "#38bdf8" },
  "Node.js": { icon: SiNodedotjs, color: "#5fa04e" },
  Express: { icon: SiExpress, color: "#9ca3af" },
  Django: { icon: SiDjango, color: "#44b78b" },
  React: { icon: SiReact, color: "#61dafb" },
  Angular: { icon: SiAngular, color: "#dd0031" },
  "Tailwind CSS": { icon: SiTailwindcss, color: "#38bdf8" },
  Flutter: { icon: SiFlutter, color: "#02569b" },
  "Apache Kafka": { icon: SiApachekafka, color: "#9ca3af" },
  Kafka: { icon: SiApachekafka, color: "#9ca3af" },
  Temporal: { icon: SiTemporal, color: "#a5b4fc" },
  Azure: { icon: TbBrandAzure, color: "#0089d6" },
  "Azure OpenAI": { icon: TbBrandOpenai, color: "#10a37f" },
  "SQL Server": { icon: DiMsqlServer, color: "#cc2927" },
  MongoDB: { icon: SiMongodb, color: "#47a248" },
  Cloudinary: { icon: SiCloudinary, color: "#3448c5" },
  Vercel: { icon: SiVercel, color: "#9ca3af" },
  Heroku: { icon: SiHeroku, color: "#7c6fd8" },
  Jira: { icon: SiJira, color: "#0052cc" },
  XSLT: { icon: SiXml, color: "#f97316" },
  Groovy: { icon: SiApachegroovy, color: "#4298b8" },
  YAML: { icon: SiYaml, color: "#cb171e" },
  REST: { icon: TbApi, color: "#22d3ee" },
  GitHub: { icon: SiGithub, color: "#9ca3af" },
};

// Logos shown in the hero marquee, in two rows.
export const marqueeRows = [
  [
    "C#",
    ".NET",
    "TypeScript",
    "Temporal",
    "Azure OpenAI",
    "Apache Kafka",
    "Azure",
    "SQL Server",
    "React",
    "Node.js",
    "Python",
  ],
  [
    "Java",
    "C++",
    "Rust",
    "MongoDB",
    "Angular",
    "Django",
    "Flutter",
    "Tailwind CSS",
    "Groovy",
    "Cloudinary",
    "Vercel",
  ],
];
